### Keras layers API:

* Layers API is used for to build the basic neural networks in Keras.
* Each A layer consists of a `tensor-in tensor-out computation function`.
* Each Layers Connect with Edge and each edge has it own Weight.
* The layer's call method and some state, held in TensorFlow variables (the layer's weights).

A Layer instance is callable, much like a function:

In [1]:
from tensorflow.keras import layers
import tensorflow as tf

In [2]:
layer = layers.Dense(32,activation='relu')

In [3]:
inputs  = tf.random.uniform(shape=(10, 20))
inputs

<tf.Tensor: shape=(10, 20), dtype=float32, numpy=
array([[2.31143713e-01, 6.91088200e-01, 4.12467122e-01, 2.68608093e-01,
        4.48799253e-01, 1.12775326e-01, 6.07395887e-01, 4.25949931e-01,
        9.71820116e-01, 6.77234292e-01, 1.37224317e-01, 1.63051009e-01,
        3.56866598e-01, 6.89522028e-01, 3.86609554e-01, 2.30122328e-01,
        7.78756976e-01, 9.94796634e-01, 1.78593278e-01, 6.61229968e-01],
       [2.18189240e-01, 2.80148625e-01, 4.89224076e-01, 2.97834396e-01,
        5.86048365e-01, 6.29269123e-01, 8.50728750e-01, 7.46493459e-01,
        2.51495838e-03, 6.46044016e-02, 1.83856487e-03, 7.86723614e-01,
        9.95537877e-01, 7.74152279e-01, 7.12137461e-01, 7.26584911e-01,
        2.62546778e-01, 7.04215646e-01, 3.58060718e-01, 3.16909790e-01],
       [7.24200010e-01, 4.64222431e-02, 3.76364470e-01, 5.91544032e-01,
        1.13884211e-01, 2.74843097e-01, 5.99124193e-01, 4.81255770e-01,
        9.88090277e-01, 4.15140152e-01, 4.84197378e-01, 3.25687885e-01,
        6.48

In [4]:
output = layer(inputs)
output

<tf.Tensor: shape=(10, 32), dtype=float32, numpy=
array([[0.00000000e+00, 6.73506021e-01, 0.00000000e+00, 9.51178074e-01,
        4.03071314e-01, 6.40464127e-01, 0.00000000e+00, 1.08605564e+00,
        5.83678901e-01, 0.00000000e+00, 7.50958622e-01, 0.00000000e+00,
        0.00000000e+00, 6.24165758e-02, 0.00000000e+00, 1.51166111e-01,
        0.00000000e+00, 2.35647827e-01, 4.15091008e-01, 5.04057884e-01,
        0.00000000e+00, 0.00000000e+00, 4.03280139e-01, 0.00000000e+00,
        0.00000000e+00, 8.21068287e-02, 3.38235199e-01, 5.02817571e-01,
        0.00000000e+00, 6.15114093e-01, 0.00000000e+00, 8.73255014e-01],
       [0.00000000e+00, 1.37954843e+00, 7.80277550e-02, 0.00000000e+00,
        0.00000000e+00, 1.63255874e-02, 0.00000000e+00, 7.31741130e-01,
        9.43756938e-01, 0.00000000e+00, 4.10410285e-01, 2.80826300e-01,
        0.00000000e+00, 0.00000000e+00, 4.07432050e-01, 0.00000000e+00,
        0.00000000e+00, 8.24117839e-01, 5.29641449e-01, 2.28913248e-01,
        7.644

* Unlike a function, though, layers maintain a state, updated when the layer receives data during training, and stored in `layer.weights`

In [5]:
layer.weights

[<tf.Variable 'dense/kernel:0' shape=(20, 32) dtype=float32, numpy=
 array([[ 0.27713412, -0.16688594,  0.02226406, -0.20453832, -0.17523682,
          0.00113747,  0.30148548, -0.21826938,  0.2531355 ,  0.08824918,
          0.26972085,  0.11309931,  0.33369488, -0.24512823,  0.10739249,
         -0.12193595, -0.3025566 , -0.15363465, -0.05507877, -0.02142432,
          0.30291373,  0.15355763,  0.07048821,  0.18982506, -0.14373045,
         -0.318381  ,  0.22062594, -0.15285014, -0.20925069,  0.11165509,
         -0.03239188,  0.04268417],
        [ 0.10273933, -0.09481218,  0.03147849,  0.3370458 , -0.3388837 ,
          0.1411503 ,  0.07547852, -0.02689999,  0.03624052, -0.33842045,
         -0.02613986,  0.22051018,  0.06359768,  0.00871271,  0.2557639 ,
          0.1162889 , -0.10204437, -0.15432215, -0.00133419,  0.05956641,
         -0.03662667, -0.06050116,  0.1938631 ,  0.1633383 , -0.22296126,
          0.00856119, -0.26789206,  0.15587434,  0.12821832,  0.03015316,
        

We have different Types of Layes:
    
    1. The base Layer class
    2. Layer activations
    3. Layer Weight 
        * Weight initializers
        * Weight regularizers(l1 and l2)
        * Weight constraints
    4. Core layers
    5. Convolution layers
    6. Pooling layers
    7. Recurrent layers
    8. Preprocessing layers
    9. Normalization layers
    10. Regularization layers
    12. Attention layers
    13. Reshaping layers
    14. Merging layers
    15. Locally-connected layers
    16. Activation layers

#### 1. The base Layer class:
    * A layer is a callable object that takes as input one or more tensors and that outputs one or more tensors.
    * It involves computation, defined in the call() method, and a state (weight variables), defined either in the constructor __init__() or in the build() method.

In [6]:
inputs = tf.keras.Input(shape=(10,))

In [7]:
d = tf.keras.layers.Dense(10)

In [8]:
x = d(inputs)

In [9]:
outputs = tf.keras.layers.Dense(1)(x)

In [10]:
model = tf.keras.Model(inputs, outputs)

In [11]:
model.weights

[<tf.Variable 'dense_1/kernel:0' shape=(10, 10) dtype=float32, numpy=
 array([[-0.13576007,  0.36232632, -0.46609223, -0.46273234, -0.21570086,
         -0.21077916, -0.37924546,  0.39514744, -0.33763057,  0.3268062 ],
        [-0.08457613,  0.53185   , -0.2507967 ,  0.5045248 ,  0.15209681,
          0.5117873 , -0.46895745,  0.25018114,  0.28919196, -0.50193465],
        [ 0.15207511, -0.5169425 , -0.06894326,  0.21552116,  0.29752958,
         -0.42565304,  0.496086  ,  0.3760957 ,  0.07220715,  0.42882723],
        [ 0.34357792,  0.12260967,  0.47259355, -0.41064045, -0.07452393,
          0.4919151 ,  0.39116848, -0.03218114, -0.30635414, -0.45995122],
        [-0.41159427, -0.4429108 , -0.13356543, -0.22047251,  0.38459468,
         -0.28797346, -0.36764368, -0.02415043, -0.04874495, -0.06041044],
        [ 0.19955844, -0.08294562,  0.05949855,  0.1794287 , -0.13017237,
          0.267089  , -0.25318658, -0.19372317, -0.01508403,  0.0985688 ],
        [ 0.28025472, -0.42579144,  

In [12]:
model.layers

In [15]:
from tensorflow import keras
keras.utils.plot_model(model,"mnist_model.png",show_shapes=True)

('Failed to import pydot. You must `pip install pydot` and install graphviz (https://graphviz.gitlab.io/download/), ', 'for `pydotprint` to work.')


In [16]:
# # Weight regularization.
model.add_loss(lambda: tf.reduce_mean(d.kernel))

#### 2. Layer activation functions
* Activations can either be used through an Activation layer, or through the activation argument supported by all forward layers: